name: navoiy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  hugeicons: ^0.0.7
  provider: ^6.1.2
  syncfusion_flutter_pdfviewer: ^27.2.5
  url_launcher: ^6.3.1
  flutter_localizations:
    sdk: flutter
  syncfusion_localizations: ^27.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/files/